spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Account service qa environment"
  contactDetails:
    name: "John Doe QA"
    email: "Ig7dF@exampleQA.com"
  onCallSupport:
    - 54321
    - 87654