CREATE TABLE IF NOT EXISTS `CUSTOMER` (
                                          `CUSTOMER_ID` INT AUTO_INCREMENT PRIMARY KEY,
                                          `NAME` VARCHAR(255) NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,
    `ADDRESS` VARCHAR(255) NOT NULL,
    `MOBILE_NUMBER` VARCHAR(255) NOT NULL,
    `CREATED_AT` DATE NOT NULL,
    `CREATED_BY` VARCHAR(255) NOT NULL,
    `UPDATED_AT` DATE DEFAULT NULL,
    `UPDATED_BY` VARCHAR(255) DEFAULT NULL
    );

CREATE TABLE IF NOT EXISTS `ACCOUNTS` (
                                          `CUSTOMER_ID` INT NOT NULL,
                                          `ACCOUNT_NUMBER` VARCHAR(255) NOT NULL,
    `ACCOUNT_TYPE` VARCHAR(255) NOT NULL,
    `BRANCH_ADDRESS` VARCHAR(255) NOT NULL,
    `CREATED_AT` DATE ,
    `CREATED_BY` VARCHAR(255) ,
    `UPDATED_AT` DATE DEFAULT NULL,
    `UPDATED_BY` VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (`CUSTOMER_ID`, `ACCOUNT_NUMBER`),
    FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`)
    );
